apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal
  labels:
    name: terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: terminal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: terminal
    spec:
      containers:
        - name: terminal
          image: {{ .Values.image }}
          # Sleep command that reacts to termination requests: https://stackoverflow.com/a/35770783
          command: ["bash", "-c", "trap : TERM INT; sleep infinity & wait"]
          workingDir: "/home/terminal-user"
          volumeMounts:
            - name: home
              mountPath: /home/terminal-user/workspace
              subPath: "workspace"
            - name: home
              mountPath: "/home/terminal-user/.kube"
              subPath: .kube
            - name: home
              mountPath: "/home/terminal-user/.vscode-server"
              subPath: .vscode-server
            - name: home
              mountPath: "/home/terminal-user/.ssh"
              subPath: .ssh
            - name: github-ssh-key
              mountPath: "/home/terminal-user/.ssh/id_rsa"
              subPath: id_rsa
              readOnly: true
            - name: loft-config
              mountPath: "/home/terminal-user/.loft/config.json"
              subPath: config.json
              readOnly: true
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      dnsPolicy: ClusterFirst
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: home
        - name: github-ssh-key
          secret:
            secretName: github-ssh-key
            items:
              - key: ssh-privatekey
                path: id_rsa
                mode: 0600
        - name: loft-config
          secret:
            secretName: loft-config
            items:
              - key: config.json
                path: config.json
